
- name: start and enable mysql service
    service:
      name: mysql
      state: started
      enabled: yes
- name: Change the auhentication plugin of mysql root user to mysql_native_password
     shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
   - name: Flush Privileges
     shell: mysql -u root -e 'FLUSH PRIVILEGES'
   - name: Sets the root password
     mysql_user:
       login_host: 'localhost'
       login_user: 'root'
       login_password: ''
       name: root
       password: "{{ mysql_root_password }}"
       state: present
   - name: Removes all anonymous user accounts
     mysql_user:
       name: ''
       host_all: yes
       state: absent
       login_user: root
       login_password: "{{ mysql_root_password }}"
