
- name: Creates new user
  mysql_user:
    login_host: 'localhost'
    name: "{{ mysql_username }}"
    password: "{{ mysql_user_password }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
- name: Creates new database
  mysql_db:
    name: "{{ mysql_database_name }}"
    login_host: 'localhost'
    state: present
    login_user: root
    login_password: "{{ mysql_username }}"
- name: Grants user  ALL access/privileges to database
  mysql_db:
    name: "{{ mysql_database_name }}"
    login_host: 'localhost'
    state: present
    login_user: root
    login_password: "{{ mysql_root_user }}"
    priv: '{{ mysql_username }}.*:ALL,GRANT'
