- name: update "apt" 
  apt: 
   update_cache: yes 
   autoclean: yes
   autoremove: yes 
- name: install (git, wget, apache, ufw, unzip, curl)
  apt:
   pkg:
   - git
   - wget
   - apache2
   - ufw
   - unzip
   - curl
