laravel_app: laravel
mysql_username: jubriladeyi
servername: 3.238.122.187
sever_email: jbadeyi@icloud.com
mysql_database_name: jubriladeyi
sever_admin: jbadeyi@icloud.com
server_name: 18.206.14.167
server_alias: node1
