- name: Composer update
  shell: composer update --no-interaction
  args:
    chdir: /var/www/html/{{ laravel_app }}

- name: Composer Install
  shell: composer update --no-interaction
  args:
    chdir: /var/www/html/{{ laravel_app }}

- name: Composer create-project
  shell: composer create-project  --no-interaction
  args:
    chdir: /var/www/html/{{ laravel_app }}

- name: Run the php -artisan migrate --force --seed command
  shell: php artisan migrate --force --seed
  args:
   chdir: /var/www/html/{{ laravel_app }}
