# - name: Copy laravel project 
#   shell: sudo mv /var/www/{{ laravel_app }} /var/www/html

# - name: Change permission
#   shell: sudo chgrp -R www-data /var/www/html/{{ laravel_app }}

# - name: Change permission
#   shell: sudo chmod -R 775 /var/www/html/{{ laravel_app }}/storage

# - name: Change permission
#   shell: sudo chmod -R ug+rwx  /var/www/html/{{ laravel_app }}/bootstrap/cache

# - name: Copy .env file
#   copy:
#     src: /var/www/html/{{ laravel_app }}/.env.example
#     dest: /var/www/html/{{ laravel_app }}/.env
#     remote_src: true

- name: Modify .env file
  template: src=.env  dest="/var/www/html/{{ laravel_app }}/.env" owner=www-data mode=0644

- name: Modify /routes/web.php file (Add frontend to laravel route)
  template: src=.web.php dest="/var/www/html/{{ laravel_app }}/routes/web.php" owner=www-data  mode=0644

- name: Copy .htacces file
  copy:
    src: .htaccess
    dest: /var/www/html/{{ laravel_app }}/.htaccess

- name: Remove default apache vhost config from sites-enabled
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: create apache vhosts for domain
  template: src=web.conf.j2 dest="/etc/apache2/sites-available/{{ laravel_app }}.conf" owner=www-data mode=0644

- name: Update a2ensite
  command: a2ensite {{ laravel_app }}

- name: Update enable apache rewrite module
  shell:  a2enmod rewrite

  notify: 
    - Restart apache
